<h1></h1>

In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:

df = pd.read_csv("datasets/Global_terrorist.csv", encoding= 'ISO-8859-1')

C:\Users\RIZEN\AppData\Local\Temp\ipykernel_10600\1170661595.py:1: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("datasets/Global_terrorist.csv", encoding= 'ISO-8859-1')

In [3]:
df

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,201712310022,2017,12,31,NaN,0,NaN,182,Somalia,11,...,NaN,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...","""Highlights: Somalia Daily Media Highlights 1 ...",START Primary Collection,0,0,0,0,NaN
181687,201712310029,2017,12,31,NaN,0,NaN,200,Syria,10,...,NaN,"""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...","""Two Russian servicemen killed in Syria mortar...",START Primary Collection,-9,-9,1,1,NaN
181688,201712310030,2017,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Maguindanao clashes trap tribe members,"" Phil...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
181689,201712310031,2017,12,31,NaN,0,NaN,92,India,6,...,NaN,"""Trader escapes grenade attack in Imphal,"" Bus...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
181690,201712310032,2017,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Security tightened in Cotabato following IED ...","""Security tightened in Cotabato City,"" Manila ...",NaN,START Primary Collection,-9,-9,0,-9,NaN

In [4]:
pip install folium

Requirement already satisfied: folium in c:\python310\lib\site-packages (0.19.5)
Requirement already satisfied: branca>=0.6.0 in c:\python310\lib\site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in c:\python310\lib\site-packages (from folium) (3.1.2)
Requirement already satisfied: numpy in c:\python310\lib\site-packages (from folium) (1.26.2)
Requirement already satisfied: requests in c:\python310\lib\site-packages (from folium) (2.31.0)
Requirement already satisfied: xyzservices in c:\python310\lib\site-packages (from folium) (2025.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python310\lib\site-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python310\lib\site-packages (from requests->folium) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python310\lib\site-packages (from requests->folium) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\python310\lib\site-packages (from requests->folium) (2023.5.7)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: C:\Python310\python.exe -m pip install --upgrade pip

In [5]:

import folium
from folium.plugins import HeatMap

In [6]:
df['country_txt'].unique()

array(['Dominican Republic', 'Mexico', 'Philippines', 'Greece', 'Japan',
       'United States', 'Uruguay', 'Italy', 'East Germany (GDR)',
       'Ethiopia', 'Guatemala', 'Venezuela', 'West Germany (FRG)',
       'Switzerland', 'Jordan', 'Spain', 'Brazil', 'Egypt', 'Argentina',
       'Lebanon', 'Ireland', 'Turkey', 'Paraguay', 'Iran',
       'United Kingdom', 'Colombia', 'Bolivia', 'Nicaragua',
       'Netherlands', 'Belgium', 'Canada', 'Australia', 'Pakistan',
       'Zambia', 'Sweden', 'Costa Rica', 'South Yemen', 'Cambodia',
       'Israel', 'Poland', 'Taiwan', 'Panama', 'Kuwait',
       'West Bank and Gaza Strip', 'Austria', 'Czechoslovakia', 'India',
       'France', 'South Vietnam', 'Brunei', 'Zaire',
       "People's Republic of the Congo", 'Portugal', 'Algeria',
       'El Salvador', 'Thailand', 'Haiti', 'Sudan', 'Morocco', 'Cyprus',
       'Myanmar', 'Afghanistan', 'Peru', 'Chile', 'Honduras',
       'Yugoslavia', 'Ecuador', 'New Zealand', 'Malaysia', 'Singapore',
       'Botswana', 'Jamaica', 'Chad', 'North Yemen', 'Andorra', 'Syria',
       'South Korea', 'United Arab Emirates', 'South Africa', 'Kenya',
       'Iraq', 'Somalia', 'Tanzania', 'Sri Lanka', 'Namibia', 'Bahamas',
       'Nigeria', 'Barbados', 'Trinidad and Tobago', 'Bangladesh',
       'Angola', 'Mauritania', 'Saudi Arabia', 'Djibouti', 'Indonesia',
       'Malta', 'Rhodesia', 'Soviet Union', 'Denmark', 'Western Sahara',
       'Guyana', 'Mozambique', 'Tunisia', 'Uganda', 'Norway', 'Lesotho',
       'Gabon', 'Libya', 'Bahrain', 'Hong Kong', 'Senegal', 'Zimbabwe',
       'Guinea', 'Grenada', 'New Hebrides', 'Belize', 'Guadeloupe',
       'Martinique', 'Vatican City', 'Albania',
       'Central African Republic', 'Seychelles', 'Dominica', 'Qatar',
       'Bulgaria', 'Suriname', 'Swaziland', 'Luxembourg', 'Iceland',
       'French Guiana', 'Falkland Islands', 'Burkina Faso',
       'New Caledonia', 'Romania', 'Niger', 'Nepal', 'Togo', 'Finland',
       'Fiji', 'Ghana', 'Maldives', 'Mauritius', 'Hungary', 'Laos',
       'Papua New Guinea', 'China', 'Liberia', 'Republic of the Congo',
       'Mali', 'Germany', 'Yemen', 'Rwanda', 'Sierra Leone', 'Cameroon',
       'Cuba', 'Croatia', 'Georgia', 'Azerbaijan', 'Madagascar',
       'Lithuania', 'Burundi', 'Ukraine', 'Moldova', 'Armenia', 'Russia',
       'Ivory Coast', 'Kazakhstan', 'Antigua and Barbuda',
       'Bosnia-Herzegovina', 'Equatorial Guinea', 'Tajikistan', 'Malawi',
       'Uzbekistan', 'Latvia', 'Estonia', 'Vietnam', 'Comoros', 'Benin',
       'Slovak Republic', 'Macedonia', 'Wallis and Futuna', 'Belarus',
       'Czech Republic', 'Slovenia', 'Gambia', 'North Korea', 'Eritrea',
       'St. Kitts and Nevis', 'French Polynesia', 'Macau', 'Kyrgyzstan',
       'Vanuatu', 'Democratic Republic of the Congo', 'Kosovo',
       'Solomon Islands', 'East Timor', 'St. Lucia', 'Guinea-Bissau',
       'Montenegro', 'International', 'Turkmenistan', 'Serbia-Montenegro',
       'Bhutan', 'Serbia', 'South Sudan'], dtype=object)

In [7]:
filter1 = df[df['country_txt'] == 'Philippines' ]

In [8]:
filter1['attacktype1_txt'].unique()

array(['Assassination', 'Bombing/Explosion', 'Unknown', 'Hijacking',
       'Armed Assault', 'Hostage Taking (Kidnapping)',
       'Facility/Infrastructure Attack',
       'Hostage Taking (Barricade Incident)', 'Unarmed Assault'],
      dtype=object)

In [9]:
filter2 = filter1[filter1['attacktype1_txt'] == 'Hostage Taking (Kidnapping)']

In [10]:
filter2

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
3134,197507250001,1975,7,25,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
3207,197508260001,1975,8,26,NaN,1,8/27/1975,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
3393,197511070001,1975,11,7,NaN,1,12/6/1975,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
3628,197602280001,1976,2,28,NaN,1,3/21/1976,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
4036,197607310001,1976,7,31,NaN,1,11/17/1976,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181441,201712200031,2017,12,20,NaN,1,NaN,160,Philippines,5,...,The victim was also a volunteer at the police ...,"""Police volunteer abducted in Bataan town,"" Ph...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
181480,201712220025,2017,12,22,NaN,0,NaN,160,Philippines,5,...,NaN,"""NPA member suspected in cop's slay - PNP chie...","""Philippines: Bato presents alleged NPA leader...","""Chief of PNP anti-kidnap unit in Luzon slain ...",START Primary Collection,0,0,0,0,NaN
181533,201712250019,2017,12,26,NaN,0,NaN,160,Philippines,5,...,NaN,"""Philippines: PNP directs men to beef up secur...","""AFP denounces NPA violation of ceasefire,"" Ma...",NaN,START Primary Collection,0,0,0,0,NaN
181602,201712280019,2017,12,28,NaN,1,NaN,160,Philippines,5,...,The victims included Teduray farmers Uzik Labi...,"""Cop slain, 5 colleagues wounded in BIFF attac...","""BIFF kills 2 kidnapped farmers, burns village...","""Philippines: Highlights of Terrorist, Counter...",START Primary Collection,0,0,0,0,NaN
181630,201712290008,2017,12,28,NaN,1,NaN,160,Philippines,5,...,NaN,"""NPA abducts police officer in Cotabato,"" Mani...","""Police official taken by armed men in North C...","""Philippines: Suspected communist rebels abduc...",START Primary Collection,0,0,0,0,NaN

In [11]:
hostage_ph = filter2.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')

In [12]:
hostage_ph

      latitude   longitude  incident_count
0     4.662801  119.399601               1
1     4.897277  119.848690               1
2     5.010223  119.747485               1
3     5.030788  119.775053               1
4     5.032286  119.772924               1
..         ...         ...             ...
412  17.611842  121.727230               1
413  18.018200  120.487600               1
414  18.225557  121.556743               1
415  18.537136  120.765284               1
416  18.561630  121.231890               1

[417 rows x 3 columns]

In [13]:
hostage_ph.max()

latitude           18.561630
longitude         126.559918
incident_count     23.000000
dtype: float64

In [14]:

#OPTIONAL, for clearer view for the Geospatial Map

hostage_ph["normalize_data"] = hostage_ph['incident_count'] - hostage_ph['incident_count'].min() / \
                                hostage_ph['incident_count'].max() - hostage_ph['incident_count']

#geospatial folium data should be formatted as a list

hostage_ph_list = hostage_ph[['latitude', 'longitude', 'incident_count']].values.tolist()

In [70]:

my_map1 = folium.Map(location = [10, 120], zoom_start = 6)

In [71]:

HeatMap(hostage_ph_list).add_to(my_map1)

In [72]:

my_map1.save('regional_analysis.html')
print("data save to regional_analysis.html")

data save to regional_analysis.html

In [73]:

my_map1

<h1>
    Insight#1
<h1>
<h1>The Hostage Taking (Kidnapping) in the Philippines in all year we can say that most of that happen in part of mindanao but we can also see that the most city that have a high heat is manila</h1

In [19]:
filter3 = df[df['country_txt'] == 'Japan']

In [20]:
filter3

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
162,197003310002,1970,3,31,NaN,1,4/3/1970,101,Japan,4,...,NaN,NaN,NaN,NaN,Hijacking DB,0,1,0,1,NaN
1851,197304250001,1973,4,25,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
2003,197308290001,1973,8,29,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
2472,197407150001,1974,7,15,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,Hijacking DB,-9,-9,0,-9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152403,201508270095,2015,8,27,NaN,0,NaN,101,Japan,4,...,The assailant was also arrested for involvemen...,"""Arrested Tokyo man implies involvement in mul...","""Anti-nuclear activist held over arson attack ...","""Police eye arson links in latest Tokyo rail f...",START Primary Collection,-9,-9,0,-9,NaN
152515,201508300094,2015,8,30,NaN,0,NaN,101,Japan,4,...,NaN,"""Arrested Tokyo man implies involvement in mul...","""Anti-nuclear activist held over arson attack ...","""Police eye arson links in latest Tokyo rail f...",START Primary Collection,-9,-9,0,-9,NaN
152744,201509050081,2015,9,5,NaN,0,NaN,101,Japan,4,...,"The other related incidents are 201508160143, ...","""Arrested Tokyo man implies involvement in mul...","""Anti-nuclear activist held over arson attack ...","""Police eye arson links in latest Tokyo rail f...",START Primary Collection,-9,-9,0,-9,NaN
155836,201511230072,2015,11,23,NaN,0,NaN,101,Japan,4,...,NaN,"""Kyodo: UPDATE2: Police Mull Sending Investiga...","""Explosion hits controversial Tokyo war shrine...","""Small blast at Tokyo's Yasukuni shrine,"" Bang...",START Primary Collection,-9,-9,0,-9,NaN
165205,201607260021,2016,7,26,NaN,0,NaN,101,Japan,4,...,Casualty numbers for this incident conflict ac...,"""5TH LEAD,"" Deutsche Presse-Agentur, July 26, ...","""Japan knife attack: Suspect wrote of wanting ...","""Letter by man accused of Japan stabbing carri...",START Primary Collection,-9,-9,0,-9,NaN

In [21]:
filter3['attacktype1_txt'].value_counts()

attacktype1_txt
Facility/Infrastructure Attack         162
Bombing/Explosion                      128
Armed Assault                           47
Unarmed Assault                         29
Assassination                           22
Unknown                                  7
Hijacking                                3
Hostage Taking (Barricade Incident)      3
Hostage Taking (Kidnapping)              1
Name: count, dtype: int64

In [22]:
filter4 = filter3[filter3['attacktype1_txt'] == 'Bombing/Explosion']

In [23]:
bombming_japan = filter4.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')

In [24]:
bombming_japan

     latitude   longitude  incident_count
0   26.228530  127.689110               1
1   34.070270  134.554844               1
2   34.487514  136.709336               1
3   34.693738  135.502165               5
4   34.784306  135.400947               1
5   35.011636  135.768029               4
6   35.181446  136.906398               3
7   35.281341  139.672200               3
8   35.346626  139.232842               1
9   35.361088  140.319273               1
10  35.367035  132.754682               1
11  35.443082  139.362489               1
12  35.443708  139.638026               2
13  35.488587  139.407673               1
14  35.493418  139.397464               1
15  35.530906  139.703051               1
16  35.571462  139.373176               1
17  35.607221  140.106270               2
18  35.680432  140.026526               2
19  35.689125  139.747742              67
20  35.714008  139.407855               1
21  35.733193  139.341805               1
22  35.738450  139.326932               3
23  35.772163  140.321777              11
24  35.776750  140.000790               1
25  35.861729  139.645482               1
26  35.979375  140.149524               1
27  36.466670  140.566670               1
28  43.062096  141.354376               1
29  43.090744  141.340726               2
30  43.090751  141.340200               1
31  43.090982  141.342221               1
32  43.096483  141.342838               1

In [25]:
#OPTIONAL, for clearer view for the Geospatial Map

bombming_japan["normalize_data"] = bombming_japan['incident_count'] - bombming_japan['incident_count'].min() / \
                                bombming_japan['incident_count'].max() - bombming_japan['incident_count']

#geospatial folium data should be formatted as a list

bombming_japan_list = bombming_japan[['latitude', 'longitude', 'incident_count']].values.tolist()

In [95]:

my_map2 = folium.Map(location = [40, 145], zoom_start = 5)

In [96]:
HeatMap(bombming_japan_list).add_to(my_map2)

In [97]:
my_map2.save('nationality_analysis.html')
print("data save to nationality_analysis.html")

data save to nationality_analysis.html

In [98]:
my_map2

 <h1>Insight #2<h1>
 <h1> The country japan have the most bombming happen into their capital tokyo <h1>

In [105]:
df['attacktype1_txt'].value_counts()

attacktype1_txt
Bombing/Explosion                      18286
Armed Assault                           3155
Assassination                           1287
Hostage Taking (Kidnapping)              946
Unknown                                  765
Facility/Infrastructure Attack           154
Hostage Taking (Barricade Incident)       24
Hijacking                                 13
Unarmed Assault                            6
Name: count, dtype: int64

In [100]:
df['country_txt'].value_counts()

country_txt
Iraq                   24636
Pakistan               14368
Afghanistan            12731
India                  11960
Colombia                8306
                       ...
International              1
Wallis and Futuna          1
South Vietnam              1
Andorra                    1
Antigua and Barbuda        1
Name: count, Length: 205, dtype: int64

In [104]:
filter5 = df[df['country_txt'] == 'Iraq']

In [106]:
filter6 = filter5[filter5['attacktype1_txt'] == 'Bombing/Explosion']

In [110]:
filter6['iyear'].value_counts()

iyear
2014    2871
2016    2760
2015    2200
2013    2128
2017    1866
2012    1118
2009     913
2010     853
2008     830
2011     816
2007     737
2006     500
2005     329
2004     196
2003      78
1995      12
1994      11
1992      10
1999       8
2000       8
1996       6
1998       6
1997       6
2002       4
2001       3
1980       3
1989       3
1983       3
1982       3
1988       2
1991       1
1984       1
1976       1
Name: count, dtype: int64

In [113]:
filter7 = filter6[filter6['iyear']  >= 2013]

In [115]:
recent5y_bombing_iraq = filter7.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
recent5y_bombing_iraq

       latitude  longitude  incident_count
0     29.167840  46.600029               1
1     29.908825  45.299141               1
2     29.976161  48.471969               1
3     30.038057  47.925789               1
4     30.116775  47.719240               1
...         ...        ...             ...
1602  36.902183  42.251461               1
1603  37.123961  44.063174               1
1604  37.175321  43.012291               1
1605  37.184525  43.298217               1
1606  37.216553  43.376226               1

[1607 rows x 3 columns]

In [117]:
#OPTIONAL, for clearer view for the Geospatial Map

recent5y_bombing_iraq["normalize_data"] = recent5y_bombing_iraq['incident_count'] - recent5y_bombing_iraq['incident_count'].min() / \
                                recent5y_bombing_iraq['incident_count'].max() - recent5y_bombing_iraq['incident_count']

#geospatial folium data should be formatted as a list

recent5y_bombing_iraq_list = recent5y_bombing_iraq[['latitude', 'longitude', 'incident_count']].values.tolist()

In [131]:

my_map3 = folium.Map(location = [35, 45], zoom_start = 6)

HeatMap(recent5y_bombing_iraq_list).add_to(my_map3)

my_map3.save('regional_analysis.html')
print("data save to regional_analysis.html")

data save to regional_analysis.html

In [133]:
my_map3

<h1>Insight 3<h1>
<h1>The country iraq bombing incident ranging from 2013 - 2017 this shows the heatmap where the most bombing happen<h1>

In [134]:
df['attacktype1_txt'].value_counts()

attacktype1_txt
Bombing/Explosion                      88255
Armed Assault                          42669
Assassination                          19312
Hostage Taking (Kidnapping)            11158
Facility/Infrastructure Attack         10356
Unknown                                 7276
Unarmed Assault                         1015
Hostage Taking (Barricade Incident)      991
Hijacking                                659
Name: count, dtype: int64

In [135]:
temp = df[df['attacktype1_txt'] == 'Assassination']

In [138]:
temp['country_txt'].value_counts()

country_txt
United Kingdom    1651
Pakistan          1406
Colombia          1343
Iraq              1287
India             1229
                  ...
Slovenia             1
Gambia               1
Macedonia            1
Norway               1
Moldova              1
Name: count, Length: 173, dtype: int64

In [139]:
filter8 = df[df['country_txt'] == 'Pakistan']

In [141]:
filter9 = filter8[filter8['attacktype1_txt'] == 'Assassination']
filter9

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
585,197011010001,1970,11,1,NaN,0,NaN,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
2795,197502080001,1975,2,8,NaN,0,NaN,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
8817,197906300002,1979,6,30,NaN,0,NaN,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,NaN
12929,198102160001,1981,2,16,NaN,0,NaN,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
14423,198109250001,1981,9,25,NaN,0,NaN,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180732,201711240028,2017,11,24,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Terror bid foiled in Landi Kotal,"" Business R...","""Carnage averted at vintage car rally as bomb ...","""Bomb targeting Khyber journalists defused,"" T...",START Primary Collection,0,0,0,0,NaN
180916,201711300015,2017,11,30,NaN,0,NaN,153,Pakistan,6,...,"The victims included Malik Wali Jan Mehsud, Ah...","""Roadside bomb kills 5 anti-Taliban fighters i...","""Peace body head among 5 killed in SWA IED bla...","""Roadside bomb kills 5 pro-govt fighters in So...",START Primary Collection,0,0,0,0,NaN
181349,201712160014,2017,12,16,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Pakistan- Haripur district nazim injured in a...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
181424,201712200009,2017,12,20,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Highlights: Pakistan Balochistan Press 21 Dec...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
181474,201712220015,2017,12,22,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Village nazim shot dead,"" DAWN Group, Decembe...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN

In [143]:
filter9['iyear'].value_counts()

iyear
1995    259
2013    161
2015    149
2014    124
1997     96
2016     82
1996     78
2012     74
2017     67
2010     44
2011     42
1994     40
2009     29
1991     24
1992     21
2008     19
1990     18
2007     10
2006      7
2000      7
1989      7
2003      6
1999      6
1988      6
2004      5
2005      5
2001      5
2002      3
1998      2
1986      2
1982      2
1981      2
1975      1
1987      1
1979      1
1970      1
Name: count, dtype: int64

In [144]:
filter10 = filter9[filter9['iyear'] >= 2010]

In [146]:
assasination_2010_onward_pakistan = filter10.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
assasination_2010_onward_pakistan

      latitude  longitude  incident_count
0    24.726417  68.260778               1
1    24.750996  67.925865               1
2    24.869619  67.244139               1
3    24.891115  67.143311             145
4    24.893379  67.423056               1
..         ...        ...             ...
340  35.457713  75.446352               1
341  35.487407  72.533736               1
342  35.515375  72.474576               1
343  35.918091  74.289803               1
344  35.920160  74.307975               1

[345 rows x 3 columns]

In [149]:
#OPTIONAL, for clearer view for the Geospatial Map

assasination_2010_onward_pakistan["normalize_data"] = assasination_2010_onward_pakistan['incident_count'] - assasination_2010_onward_pakistan['incident_count'].min() / \
                                assasination_2010_onward_pakistan['incident_count'].max() - assasination_2010_onward_pakistan['incident_count']

#geospatial folium data should be formatted as a list

assasination_2010_onward_pakistan_list4 = assasination_2010_onward_pakistan[['latitude', 'longitude', 'incident_count']].values.tolist()

In [155]:

my_map4 = folium.Map(location = [30, 70], zoom_start = 6)

HeatMap(assasination_2010_onward_pakistan_list4).add_to(my_map4)

my_map4.save('regional_analysis.html')
print("data save to regional_analysis.html")

data save to regional_analysis.html

In [156]:
my_map4

<h1>Insight #4<h1>
    <h1>Assasination attack in the country pakistan in 2010 onward the most of this kind of  attack happen in karachi(Karachi (كراچى) is the capital of the province of Sindh, and the largest city in Pakistan)<h1>

In [158]:
temp1 = df[df['attacktype1_txt'] == 'Hijacking']

In [159]:
temp1

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
12,197001080001,1970,1,8,NaN,0,NaN,98,Italy,8,...,NaN,NaN,NaN,NaN,Hijacking DB,-9,-9,1,1,NaN
135,197003140004,1970,3,14,NaN,1,3/15/1970,217,United States,1,...,McKay and Glatkowski hijacked the ship by deta...,"""Mystery of the SS Columbia Eagle Hijacking,"" ...","Tad Szulc, ""U.S. Arms Ship to Thailand Seized ...","""U. S. Arms Ship, Freed, Leaves Cambodia,"" New...",Hewitt Project,-9,-9,0,-9,NaN
162,197003310002,1970,3,31,NaN,1,4/3/1970,101,Japan,4,...,NaN,NaN,NaN,NaN,Hijacking DB,0,1,0,1,NaN
379,197007010003,1970,7,1,NaN,0,NaN,30,Brazil,3,...,NaN,NaN,NaN,NaN,Hijacking DB,-9,-9,0,-9,NaN
421,197007220001,1970,7,22,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,Hijacking DB,-9,-9,0,-9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180347,201711090026,2017,11,9,2017-11-09 00:00:00,1,NaN,4,Afghanistan,6,...,NaN,"""AFGHANISTAN UN - Suspected Taliban fighters s...",NaN,NaN,START Primary Collection,0,1,1,1,NaN
180404,201711120004,2017,11,11,NaN,0,NaN,113,Libya,10,...,NaN,"""Hosted Product: Libya Counterterrorism Weekly...","""Hosted Product: Libya Daily Digest November 1...",NaN,START Primary Collection,0,0,0,0,NaN
180706,201711230026,2017,11,23,NaN,0,NaN,195,Sudan,11,...,NaN,"""Man Killed, Hijacks In North And South Darfur...","""Sudan weapon collectors arrest 'dozens' of ar...",NaN,START Primary Collection,-9,-9,0,-9,NaN
180707,201711230027,2017,11,24,2017-11-24 00:00:00,0,NaN,195,Sudan,11,...,NaN,"""Man Killed, Hijacks In North And South Darfur...","""Sudan weapon collectors arrest 'dozens' of ar...",NaN,START Primary Collection,-9,-9,0,-9,NaN
181022,201712030022,2017,12,3,NaN,1,NaN,4,Afghanistan,6,...,NaN,"""DA'ISH supporters torch shrine in Afghan west...",NaN,NaN,START Primary Collection,0,1,0,1,NaN

In [161]:
temp1['country_txt'].value_counts()

country_txt
Sudan                               45
India                               43
Philippines                         34
Colombia                            33
Somalia                             31
                                    ..
Singapore                            1
Azerbaijan                           1
Ecuador                              1
Armenia                              1
Democratic Republic of the Congo     1
Name: count, Length: 105, dtype: int64

In [162]:
filter11 = df[df['attacktype1_txt'] == 'Hijacking']

In [177]:
filter12 = filter11[(filter11['country_txt'] == 'Sudan') | (filter11['country_txt'] == 'India')]

In [178]:
filter12

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
1186,197202220004,1972,2,22,NaN,0,NaN,92,India,6,...,NaN,NaN,NaN,NaN,Hijacking DB,1,1,1,1,NaN
5327,197709280004,1977,9,28,NaN,0,NaN,92,India,6,...,NaN,NaN,NaN,NaN,Hijacking DB,1,1,1,1,NaN
14447,198109290003,1981,9,29,NaN,1,9/30/1981,92,India,6,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
16870,198208200020,1982,8,20,NaN,1,8/21/1982,92,India,6,...,NaN,NaN,NaN,NaN,Hijacking DB,0,0,0,0,NaN
22126,198405210013,1984,5,21,NaN,0,NaN,92,India,6,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177752,201708070039,2017,8,7,NaN,0,NaN,195,Sudan,11,...,NaN,"""Aid Vehicle Hijacked In North Darfur Capital ...",NaN,NaN,START Primary Collection,-9,-9,1,1,NaN
178282,201708250038,2017,8,26,NaN,0,NaN,92,India,6,...,Casualty numbers conflict across sources. Foll...,"""India: Posters Signed by Gorkha Liberation Ar...","""Third blast in Darjeeling in a week, no one i...","""Blast on National Highway 10 to Sikkim,"" Onei...",START Primary Collection,0,0,0,0,NaN
179719,201710150026,2017,10,15,NaN,0,NaN,92,India,6,...,The victims included Ghasi Pangi.,"""Maoists hijack launch with grocery for IRB fo...","""Maoists abduct Gaon Sathi in Kandhamal,"" New ...",NaN,START Primary Collection,0,0,0,0,NaN
180706,201711230026,2017,11,23,NaN,0,NaN,195,Sudan,11,...,NaN,"""Man Killed, Hijacks In North And South Darfur...","""Sudan weapon collectors arrest 'dozens' of ar...",NaN,START Primary Collection,-9,-9,0,-9,NaN
180707,201711230027,2017,11,24,2017-11-24 00:00:00,0,NaN,195,Sudan,11,...,NaN,"""Man Killed, Hijacks In North And South Darfur...","""Sudan weapon collectors arrest 'dozens' of ar...",NaN,START Primary Collection,-9,-9,0,-9,NaN

In [179]:
hijacking_sudan = filter12.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
hijacking_sudan

     latitude  longitude  incident_count
0    9.089398  29.457171               1
1   11.291012  23.191802               1
2   11.294612  23.393656               1
3   11.452522  26.129593               1
4   11.575898  24.578336               1
..        ...        ...             ...
63  33.720251  74.861786               1
64  33.721287  74.831062               1
65  33.909642  74.895737               1
66  34.083740  74.789902               1
67  34.447500  74.584722               1

[68 rows x 3 columns]

In [180]:
#OPTIONAL, for clearer view for the Geospatial Map

hijacking_sudan["normalize_data"] = hijacking_sudan['incident_count'] - hijacking_sudan['incident_count'].min() / \
                                hijacking_sudan['incident_count'].max() - hijacking_sudan['incident_count']

#geospatial folium data should be formatted as a list

hijacking_sudan_list = hijacking_sudan[['latitude', 'longitude', 'incident_count']].values.tolist()

In [188]:

my_map5 = folium.Map(location = [15, 30], zoom_start = 3)

HeatMap(hijacking_sudan_list).add_to(my_map5)

my_map5.save('regional_analysis.html')
print("data save to regional_analysis.html")

data save to regional_analysis.html

In [190]:
my_map5

<h1>Insight#5<h1>
<h1>this 2 country have the most record happen in hijacking the Sudan and India this is the heatmap for two country<h1>